### ISSUE TITLE
2 Errors in Convert.php

### ISSUE THREAD

**Issue by MaulaSufa** [MichaelBelgium/Youtube-to-mp3-API#2]
When I try to converting, I got message like this:

` {"error":true,"message":"The command \"'\/usr\/local\/bin\/youtube-dl' 'https:\/\/www.youtube.com\/watch?v=pVLmZMjxfjw' '--no-playlist' '--ignore-config' '--write-info-json' '--extract-audio' '--audio-format=mp3' '--audio-quality=0' '--output=%(id)s.%(ext)s'\" failed.\n\nExit Code: 1(General error)\n\nWorking directory: \/var\/www\/html\/yt2mp3\/download\/\n\nOutput:\n================\n[youtube] pVLmZMjxfjw: Downloading webpage\n\n\nError Output:\n================\nWARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.\nERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))\n"}`

**Comment by MaulaSufa** [comment]
Please help me :(

**Comment by MaulaSufa** [comment]
@MichaelBelgium

**Comment by MichaelBelgium** [comment]
Are you hosting it yourself or using my website to convert? I suppose not mine because I don't see that error. You should set your LC_ALL environment variable and restart the server

**Comment by MaulaSufa** [comment]
@MichaelBelgium I make my own API.. but it's shows errors like that...
And btw.. how to set LC_ALL environment?

**Comment by MichaelBelgium** [comment]
Google can help, Execute the command `export LC_ALL=en_US.UTF-8` (if you have a linux based server)

**Comment by MaulaSufa** [comment]
> Google can help, Execute the command `export LC_ALL=en_US.UTF-8` (if you have a linux based server)

I have Debian/Linux based server.. I already try that and restart my server.
and i still got error like this:
`{"error":true,"message":"The command \"'\/usr\/local\/bin\/youtube-dl' 'https:\/\/www.youtube.com\/watch?v=pVLmZMjxfjw' '--no-playlist' '--ignore-config' '--write-info-json' '--extract-audio' '--audio-format=mp3' '--audio-quality=0' '--output=%(id)s.%(ext)s'\" failed.\n\nExit Code: 1(General error)\n\nWorking directory: \/var\/www\/html\/yt2mp3\/download\/\n\nOutput:\n================\n[youtube] pVLmZMjxfjw: Downloading webpage\n\n\nError Output:\n================\nWARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.\nERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))\n"}`

Can i use your youtube converter for my samp server?

**Comment by MichaelBelgium** [comment]
Whats the output of the command `locale` on your server? And yes, if you really can't fix it you can use mine

**Comment by MaulaSufa** [comment]
@MichaelBelgium 

> LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=en_GB.UTF-8

**Comment by MichaelBelgium** [comment]
Looks fine for me, strange

**Comment by johnny-stevie** [comment]
@MichaelBelgium I am using your website, but i get the same error as @MaulaSufa : 
`{"error":true,"message":"The command \"'/usr/local/bin/youtube-dl' 'https://www.youtube.com/watch?v=R65ECY8guOc' '--no-playlist' '--ignore-config' '--write-info-json' '--skip-download'\" failed.\n\nExit Code: 1(General error)\n\nWorking directory: /var/www/html/michael/ytconverter/download/\n\nOutput:\n================\n[youtube] R65ECY8guOc: Downloading webpage\n\n\nError Output:\n================\nWARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.\nERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\n"}`
Can you help me?
Any help appreciated.

**Comment by MichaelBelgium** [comment]
@MaulaSufa error is `ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))`

@johnny-stevie Your error is `ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

Its not really the same. Gotta pay attention to the last lines. 
The error "Too Many Requests" is simply due youtube-dl calling whatever too much to convert the video. If you're using the converter on my domain then this happens frequently. Just because a lot of people are using it. I've been considering to work with api-keys or making it a paid service. The only solution i've always did is disabling the converter for a day every time.

**Comment by johnny-stevie** [comment]
Thanks for your reply, I missed the last bit of the error message. Your
domain is probably my best shot at doing any YouTube to MP3 converting
cause if I set up an API on free hosting, it would get overloaded
very quickly. I can't really use your source code directly as I am building
a hybrid app in js so it wouldn't really work.
Hope you understand and keep your domain free. Your API is very good and
easy to use, keep going with it!
Btw, was the error coming ytdl and not from your domain crashing due to
network traffic?
Thanks!

**Comment by MichaelBelgium** [comment]
@johnny-stevie  Isn't it possible to just send an ajax request in js? And yes, that error is generated by youtube-dl. It's the output of the command `/usr/local/bin/youtube-dl https://www.youtube.com/watch?v=R65ECY8guOc --no-playlist --ignore-config --write-info-json --skip-download` - which is shown in the error too

**Comment by johnny-stevie** [comment]
Not really, because I'm requesting the MP3 file from the app, it does not
have all the native features of normal js. Instead I'm sending a get req to
obtain the MP3 file.
